database:
  host: "localhost"
  port: 3306
  user: "root"
  password: "NewPass@123!"
  name: "12345"
  table: "12345"

data_lists:
  streets:
    - 龙山街道
    - 泉河街道
    - 怀柔镇
    - 庙城镇
    - 北房镇
    - 雁栖镇
    - 桥梓镇
    - 长哨营乡
    - 汤河口镇
    - 喇叭沟门乡
    - 杨宋镇
    - 宝山镇
    - 渤海镇
    - 琉璃庙镇
    - 九渡河镇
    - 怀北镇
  units:
    - 环卫公司
    - 怀胜公司
    - 示范区管委会
    - 国资公司
    - 总工会
    - 体育局
    - 园林绿化局
    - 商务局
    - 医保局
    - 卫健委
    - 教委
    - 民政局
    - 人保局
    - 消防救援局
    - 市场监管局
    - 经信局
    - 水务局
    - 交通局
    - 住建委
    - 长城伟业公司
    - 城管委
    - 科学城公司
    - 城管执法局
    - 残联
    - 农业农村局
    - 生态环境局
    - 文旅局
    - 公路分局
    - 信访办
    - 退役军人局
    - 规自分局
    - 投促中心
    - 发改委